version: '3'
services:
  rental-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rental-manager
    restart: always
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    volumes:
      - '/app/node_modules'
      - '.:/app'
    networks:
          - vue-network
networks:
  vue-network:
    driver: bridge